### ISSUE TITLE
سكشن لليدرز  ظبطوا الدنيا + صورهم هنا 

### ISSUE THREAD

**Issue by Hamdysaad20** [levelupesg/WebsiteReact#69]
Don Liyanage
Ekta Soni
Hamdy Saad
Prasad Bhalerao

https://drive.google.com/drive/folders/1RupuzHb1VIsPELQvR3F19EI3iKLjrXLL?usp=sharing

**Comment by devbn3li** [comment]
فين محمد على يرجوله

**Comment by Hamdysaad20** [comment]
@devbn3li  خلاص هنبوظ هتبقي عربي وميمز كمان
